import { resolve } from 'node:path'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./tests/setup.ts'],
    include: ['tests/**/*.{test,spec}.{ts,tsx}', 'src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['e2e/**', 'node_modules/**'],
    coverage: {
      provider: 'v8',
      include: ['src/**'],
      exclude: [
        'src/routeTree.gen.ts',  // auto-generated by TanStack Router
        'src/**/*.md',           // README placeholders (cause parse errors)
        'src/index.css',         // CSS, not executable
        'src/main.tsx',          // entry point, just bootstraps React
        'src/types/**',          // type-only declarations, no runtime code
        'src/components/ui/**',  // shadcn auto-generated components
      ],
    },
  },
})
