import { resolve } from 'node:path'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['e2e/**', 'node_modules/**'],
    coverage: {
      provider: 'v8',
      include: ['src/**'],
      exclude: [
        // auto-generated by TanStack Router
        'src/routeTree.gen.ts',

        // README placeholders (cause parse errors)
        'src/**/*.md',

        // CSS, not executable
        'src/index.css',

        // entry point, just bootstraps React
        'src/main.tsx',

        // type-only declarations, no runtime code
        'src/types/**',

        // shadcn auto-generated components
        'src/components/ui/**',

        // singleton config, no logic to unit test
        'src/lib/api-client.ts',
        'src/lib/query-client.ts',

        // wiring/bootstrap (providers, router, env parsing)
        'src/app/**',

        // covered by E2E tests
        'src/routes/**',
        'src/features/**/components/**',
        'src/features/**/services/**',
      ],
    },
  },
})
